name: my_blog
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ==============Start支持iOS Android web win linux macOS 的库Start=========================
  cupertino_icons: ^1.0.2
  dio: ^4.0.0 # 网络库
  flutter_screenutil: ^5.0.0 # 屏幕适配
  pull_to_refresh: ^2.0.0  # 刷新组件
  url_launcher: ^6.0.3 # 拉起url
  event_bus: ^2.0.0 # 事件总线
  get: ^4.1.4 # 状态管理
  shared_preferences: ^2.0.5 # 磁盘 键值 存取
  card_swiper: ^1.0.2 # 轮播
  bot_toast: ^4.0.1 # 一个真正意义上的flutter Toast库

  flutter_markdown: ^0.6.6
  photo_view: ^0.11.1 # 图片预览
  device_info_plus: ^1.0.0  # 设备信息
  flutter_staggered_grid_view: ^0.4.0
  equatable: ^2.0.3
  reorderables: ^0.4.1

  responsive_framework: ^0.1.4

  # 工具
  dio_log : ^2.0.0 # app内抓包工具
  logger: ^1.0.0 # 日志库

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - static/
